In [2]:
import numpy as np

# Etapa da criação de um Numpy Array

O Numpy array é de 10 a 100 vezes mais rápido do que um array do Python puro, além de utilizar menos memória.

Os Numpy arrays não arrays N-Dimensionais

É possível transformar qualquer sequência de dados em python em um np.array

Vale ressaltar que o numpy array é um objeto homogêneo, ou seja, todos os elementos devem ser do mesmo tipo.

Todo array tem um corpo, que como podemos ver ao imprimir o np.array na tela, é composto por uma tupla que indica o tamanho de cada **dimensão** desse array.

Temos também o **dtype** do array, que é um objeto que descreve o tipo de dado daquele array.

In [3]:
data1 = [6,5,4,3,2,1]

In [4]:
array1 = np.array(data1)

In [5]:
array1

array([6, 5, 4, 3, 2, 1])

In [6]:
array1.dtype

dtype('int64')

In [7]:
data2 = np.random.randn(4,4)

In [8]:
data2

array([[ 0.10822767,  1.40463847, -1.27875749, -1.0516809 ],
       [ 0.44793419,  0.46417408,  1.07785936,  0.18067272],
       [-0.4827358 ,  0.51235675, -2.76023912, -0.20457037],
       [ 0.51182017,  0.11428956, -1.12107425,  0.84367641]])

In [9]:
data2.dtype

dtype('float64')

Sequências aninhadas como uma lista de listas de mesmo tamanho serão convertidas em um array multidimensional

In [10]:
data3 = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
array2 = np.array(data3)

In [12]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

In [14]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

Para descobrir a dimensão de um np.array podemos utilizar a função .ndim

In [15]:
array2.shape

(3, 3)

In [16]:
array2.ndim

2

In [17]:
array3.shape

(3, 2, 3)

In [18]:
array3.ndim

3

### Arange é uma versão da função range do python

Podemos utilizá-la para criar uma determinada sequência de valores.

**Lembrando que a contagem de índices de arrays em python começa do zero.**

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

## Tabela de Funções padrões para criação de arrays

Vale ressaltar que todas essas tabelas foram retiradas do Livro: Python para Análise de Dados - McKinney

|Função|Descrição|
|-------|---------|
|**array**| Converte dados de entrada em um ndarray.|
|**asarray**| Converte a entrada para um ndarray, mas não copia se a entrada já foi um ndarray|
|**arange**|Funciona como a função range do python, porém devolve um ndarray ao invés de um array de python|
|**ones, ones_like**| Gera um array somente com 1s, com o formato de dtype especificados. **ones_like** aceita outro array e gera um array de uns com o mesmo formato e o mesmo dtype|
|**zeros, zeros_like**| Funciona como o ones e ones_like, porém retorna arrays de 0|
|**empty, empty_like**|Cria novos arrays alocando nova memória, mas ão preenche nenhum valor, como ones e zeros|
|**full, full_like**|Gera um array com o formato e o dtype especificados, com todos os valores definidos com o "valor de preenchimento" indicado. **full_like** aceita outro array e gera um array preenchido com o mesmo formato e o mesmo dtype|
|**eye, identity**|Cria uma matriz-identidade quadrada NxN (1s na diagonal e 0s nas demais posições|

## Tabela com tipos de dados para ndarrays

|Função|Descrição|
|-------|---------|
|**int8, unit8**| Tipos inteiros de 8 bits (1 byte)|
|**int16, uint16**| Tipos inteiros ded 16 bits com e sem sinal|
|**int32, uint32**|Tipos inteiros de 32 bits com e sem sinal|
|**int64, uint64**|Tipos inteiros de 64 bits com e sem sinal|
|**float16**|Ponto flutuante com metade da precisão|
|**float32**|Ponto flutuante com precisão única, compatível com float de C|
|**float64**|Ponto flutuante com dupla precisão, compatível com o double de C e o objeto float de Python|
|**float128**|Ponto flutuante com precisão estendida|
|**complex64, complex128, complex256**| Números complexos representados por dois floats de 32, 64 ou 128, respectivamente|
|**bool**|Valores True ou False|
|**object**|Tipos de Objetos de Python, um valor pode ser qualquer objeto Python|
|**string_**|Tipo string ASCII de tamanho fixo (1 byte por caractere), se quiser criar um string de tamanho 10, utilizar "S10"|
|**unicode**|Tipo unicode de tamanho fixo, a mesma semântica de especificação que usamos em **string_**, "U10" por exemplo|


Parei na página 128 do livro