In [25]:
import numpy as np

# Etapa da criação de um Numpy Array

O Numpy array é de 10 a 100 vezes mais rápido do que um array do Python puro, além de utilizar menos memória.

Os Numpy arrays não arrays N-Dimensionais

É possível transformar qualquer sequência de dados em python em um np.array

Vale ressaltar que o numpy array é um objeto homogêneo, ou seja, todos os elementos devem ser do mesmo tipo.

Todo array tem um corpo, que como podemos ver ao imprimir o np.array na tela, é composto por uma tupla que indica o tamanho de cada **dimensão** desse array.

Temos também o **dtype** do array, que é um objeto que descreve o tipo de dado daquele array.

In [61]:
data1 = [6,5,4,3,2,1]

In [62]:
array1 = np.array(data1)

In [63]:
array1

array([6, 5, 4, 3, 2, 1])

In [64]:
array1.dtype

dtype('int64')

In [65]:
data2 = np.random.randn(4,4)

In [66]:
data2

array([[-0.47994773, -0.04347852,  0.48728507, -0.49173004],
       [-1.31663396,  0.24744195, -0.18313381, -0.43051531],
       [-0.17094107, -0.07844401, -0.71261076,  0.00244944],
       [-0.45009612,  0.92859786,  0.8375331 , -1.31067672]])

In [67]:
data2.dtype

dtype('float64')

Sequências aninhadas como uma lista de listas de mesmo tamanho serão convertidas em um array multidimensional

In [73]:
data3 = [[1,2,3], [4,5,6], [7,8,9]]

In [74]:
array2 = np.array(data3)

In [75]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

In [91]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

Para descobrir a dimensão de um np.array podemos utilizar a função .ndim

In [86]:
array2.shape

(3, 3)

In [88]:
array2.ndim

2

In [98]:
array3.shape

(3, 2, 3)

In [99]:
array3.ndim

3

### Arange é uma versão da função range do python

Podemos utilizá-la para criar uma determinada sequência de valores.

**Lembrando que a contagem de índices de arrays em python começa do zero.**

In [100]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

*obs: continuar da página 125 do livro Python para Análise de Dados